### PR TITLE
Add support for configurable fahclient, fahcontrol, and fahviewer local service

### PR DESCRIPTION
**Pull request by dmc5179**
Add support for configurable fahclient, fahcontrol, and fahviewer local service.

This does not yet include support for the containerized versions of the fahclient, fahcontrol, or fahviewer applications.

### CODE REVIEW

**Review by ajacocks — APPROVED** [review]
Do you want to default to 7.6.2 or 7.6.3?

**Comment by dmc5179** [comment]
At the time that I wrote this there wasn't a 7.6.3 version on their site for either deb or RPM, I can't remember which one. I didn't want that to cause an issue with the playbooks by defaulting to that. Now there is a 7.6.5 for both so I can update to that and submit a new PR. Sorry for the pace. They are releasing very fast. I've asked on slack if there is a changelog or something that says what it changing in each one. They are not using the rpm changelog feature.

**Comment by jwesterd-redhat** [comment]
+1 on changelog.

Should we request init start install Be relegated to tar file+script and
leave rpm tied to systemd only?

Did see a "latest" rpm being dropped next to the list of rpms  .... could
use that?

Extravar for version?

**Comment by dmc5179** [comment]
@jwesterdale-rh The latest RPM is just a symbolic link to one of the other RPMs. It shows that the FAH team has no idea what an RPM is. Tar files tend to have a latest pointer link but not RPMs. The "latest" RPM won't change anything related to systemd or systemv. Dropping down to a tar ball install instead of using an RPM will certainly resolve the chkconfig dependency issue by ensuring that no dependencies are pulled in at all. This is probably not what we want to do.

**Pull request merged**
