### PR TITLE
moved config template to role level, added versions to dependencies, …

### PR DESCRIPTION
**Pull request by westerj**
…added docs
added become: true to tasks in playbook main.yml
changed include to include_task for gpu.yml
commented out static - didn't seem to apply and it generated error messages.
debug line to show/confirm the version number working.
restarted FAHClient to rewrite the config.xml file. (template was messy)
moved config.xml to the role level.

I removed the RPM on 3 servers, and ran it

all came back to life. FAHControl node didn't mind. SystemInfo even updated.

All CPU's in one slot for the moment.
NVidia conversion is next. Tomorrow.
Tested On RHEL7.latest and RHEL8.latest.

### CODE REVIEW

**Comment by dmc5179** [comment]
@westerj 2 things:

Please remove what appears to be a debug statement from the playbook here:
roles/fahclient/tasks/dependencies.yaml
- name: JW echo version/url

roles/fahclient/tasks/dependencies.yaml contains a task to restart the FAHClient service right before
- import_tasks: service.yaml
￼  when: local_service | bool

which are the tasks that actually install the service if this is a local install. We can't call a service restart before the service is installed. This probably worked on a system you tested because the service was already installed but this would fail on a fresh system.

**Comment by westerj** [comment]
Excellent. Thanks.

The service restart cleans up the config.xml... interesting.

Saw the note sbout not using client type: beta. Had been, but removed.
Think i had mentioned it, but should redact.

Thanks for review.

**Comment by jwesterd-redhat** [comment]
Updated as requested. TY

**Comment by jwesterd-redhat** [comment]
updated the file version format.. not sure if the latest.rpm will work... as it does not confer the RPM name as (for example) fahclient...

**Review by ajacocks — APPROVED** [review]
Thanks for all the work on documentation!

**Comment by jwesterd-redhat** [comment]
added V 7.6.9 and 7.6.10.  Not sure it the latest (public/beta) will work.

**Pull request merged**
